---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Allure.
--- DateTime: 2024/3/17 15:53
---

if(redis.call('get',KEYS[1])== ARGV[1]) then
    return redis.call('del',KEYS[1])
end
return 0